version: '2'
networks:
  miner:
    driver: bridge
services:
  miner:
    image: miner
    build: ./miner
    depends_on:
      - rabbitmq
    ports:
      - "6000:6000"
    environment:
      - PUBLISH=ingest
    networks:
      - miner
  mitie:
    image: mitie
    build: ./mitie
    depends_on:
      - rabbitmq
    environment:
      - CONSUME=ingest
      - PUBLISH=mitie
    networks:
      - miner
  predpatt:
    image: predpatt 
    build: ./predpatt
    depends_on:
      - rabbitmq
    environment:
      - CONSUME=mitie
      - PUBLISH=predpatt
    networks:
      - miner
  relevancy:
    image: relevancy
    build: ./relevancy
    depends_on:
      - rabbitmq
    environment:
      - CONSUME=predpatt
      - PUBLISH=relevancy
    networks:
      - miner
  quad:
    image: quad
    build: ./quad
    depends_on:
      - rabbitmq
    environment:
      - CONSUME=relevancy
      - PUBLISH=quad
    networks:
      - miner
  collector:
    image: collector
    build: ./collector
    depends_on:
      - rabbitmq
    environment:
      - CONSUME=actors
    networks:
      - miner
    volumes:
      - ./data:/src/data
  rabbitmq:
    image: rabbitmq:alpine
    expose:
      - "5672"
    networks:
      - miner
