version: '2'
networks:
  eventminer_miner:
    external: true
services:
  hypnos:
    image: hypnos
    build: .
    environment:
      - CONSUME=quad
      - PUBLISH=actors
    networks:
        - eventminer_miner
  ccnlp:
    image: caerusassociates/ccnlp:1.0.0
    networks:
        - eventminer_miner
  petrarch:
    build: petrarch/.
    networks:
        - eventminer_miner
